# Generated by Django 2.1.7 on 2019-04-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='thumb',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.FileField(blank=True, default='null', upload_to=''),
        ),
    ]
